services:
  db:
    image: postgres:13
    container_name: api_agenconsul_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: agenconsul
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: